PAGE_SIZE_FOR_LIST_FILES:int = 100

# names
WORKSHEET_SAMPLE_COPY_NAME: str = "Copy of WORKSHEET_SAMPLE"
WORKSHEET_SAMPLE_NAME: str = "WORKSHEET_SAMPLE"
DALAHOP_FOLDER_NAME: str = "DALASHOP"
ARTANDCRAFT_FOLDER_NAME: str = "ART_CRAFT"
CAFFE_FOLDER_NAME: str = "DALA_CAFFE"

# ids
DAY_TEMPLATE_ID = "1Xh5ZAwsr_SaF2GHQHmJZwhdZnQM-adSFiMrAAB7yc3s"
MONTHLY_REPORT_TEMPLATE_ID: str = "1UvJ9bcsn6U2n9joXC55nEwPb0ifpRu1gUwAPe2og77g"
NESTED_FILE_ID: str = "1j6xLhBBkicEneFIlXWLhB56V0DMJiIxRA4vDDDhAeHI"
NESTED_FOLDER_ID: str = "1PNDivjpslR_dA2a5yZlE5l9lbfr7XWa4"
ROOT_FOLDER_ID: str = "1HlMXMD94ok0mFEP8k7QoGY3JZX8YjAQS"
DALASHOP_FOLDER_ID:str = "1kjWENsaqJWC7PeSXVD7IP5yVe4GZp1VP" 
ART_CRAFT_FOLDER_ID: str = "1KtFC0c9PKaaX5r65ZKOihWigFwc2gYny"
DALA_CRAFFE_FOLDER_ID: str = "1VpgSGa9LzMKPFjLCOBs6vQazdawqOzHw"